### ISSUE TITLE
License

### ISSUE THREAD

**Issue by RemiCollin** [incraigulous/contentful-laravel#4]
Just noticed the package lacks the License definition, so theorically, I can't use it in a project ;)

**Comment by incraigulous** [comment]
Just noticed that this morning. I've added it already but haven't committed
it yet. Working on some other things at the same time. I'll probably commit
it in the morning. In the meantime, I, Craig Wann, give you permission to
use the package in your project(s).. ;)

**Comment by RemiCollin** [comment]
cool, i'm reassured :)

**Comment by incraigulous** [comment]
I've added the license definition to composer.json.
